### ISSUE TITLE
Registering codecs

### ISSUE THREAD

**Issue by jurepetrovic** [ralscha/bsoncodec#1]
Hello, 

I'm trying to register these codec classes with mongo db driver 3.8.0 but no success. 

`CodecRegistry pojoCodecRegistry = 
				fromRegistries(MongoClientSettings.getDefaultCodecRegistry(),
                fromProviders(PojoCodecProvider.builder().automatic(true).build()),
                fromCodecs(new ZonedDateTimeStringCodec())); // added ZonedDateTime codec
		
db = db.withCodecRegistry(pojoCodecRegistry);`

Shouldn't that line with fromCodecs() be enough?

**Comment by ralscha** [comment]
Hi
It should be enough. But if I'm not completely wrong order matters. First codec wins. 
Maybe the PojoCodecProvider tries to serialize ZonedDateTime, they are Pojos too.  Try something like this:

```
CodecRegistry codecRegistry = CodecRegistries.fromRegistries(
        MongoClientSettings.getDefaultCodecRegistry(),
        CodecRegistries.fromCodecs(new ZonedDateTimeStringCodec()),
        CodecRegistries.fromProviders(PojoCodecProvider.builder().automatic(true).build())
);
```

The mongodb java driver 3.7 introduced a few JSR310 codecs. They will be registered when you call
`getDefaultCodecRegistry()`, but `ZonedDateTime` is not part of this support.
But if a future version of the mongodb java driver introduces that you have to move the `fromCodecs` line to the top.
```
            Class.forName("java.time.Instant"); // JSR-310 support canary test.
            putCodec(new InstantCodec());
            putCodec(new LocalDateCodec());
            putCodec(new LocalDateTimeCodec());
            putCodec(new LocalTimeCodec());
```

**Comment by jurepetrovic** [comment]
Hello, 

thanks for the answer. I read just yesterday that the order matters :)
So, I changed it like this and it works. Which is esentially your answer. 
Thank you!

 ```
CodecRegistry pojoCodecRegistry = 
			fromRegistries(MongoClientSettings.getDefaultCodecRegistry(),
			fromCodecs(new ZonedDateTimeStringCodec()), // added ZonedDateTime codec
			// automatic provider should be last in the list
		        fromProviders(PojoCodecProvider.builder().automatic(true).build())); 

db = db.withCodecRegistry(pojoCodecRegistry);

```

**Comment by ralscha** [comment]
I think to be future proof add the `ZonedDateTimeStringCodec` first. When the mongodb driver adds support for ZonedDateTime in the future your application will not be affected

```
CodecRegistry pojoCodecRegistry = 
   		fromCodecs(new ZonedDateTimeStringCodec()), // added ZonedDateTime codec
                fromRegistries(MongoClientSettings.getDefaultCodecRegistry(),   		
   		// automatic provider should be last in the list
   	        fromProviders(PojoCodecProvider.builder().automatic(true).build())); 
```

**Comment by jurepetrovic** [comment]
Ok, I changed it. But for the sake of completeness, I'm posting syntactically correct version :)

```java

CodecRegistry pojoCodecRegistry = 
		
	fromRegistries(
		fromCodecs(new ZonedDateTimeStringCodec()), // added ZonedDateTime codec
		MongoClientSettings.getDefaultCodecRegistry(), 
	        // automatic provider should be last in the list
	        fromProviders(PojoCodecProvider.builder().automatic(true).build())
	); 
		
db = db.withCodecRegistry(pojoCodecRegistry);

```


There is another funny thing I noticed. Certain variable names in POJOs don't get serialized. 
If I used this name, the field did not get serialized. 

```java
private ZonedDateTime hDate;
```

However, changing it to suddenly started working. Of course, I changed the getters and setters too. 

```java
private ZonedDateTime humanDate;
```

Is there any limitation as to variable names in POJOs in order to get serialized? 

Thank you in advance for your time and effort!
Jure

**Comment by ralscha** [comment]
Sorry, I don't have any experience with the PojoCodecProvider.
